---
- name: Configure Ansible Tower for demo
  hosts: 127.0.0.1
  connection: local
  become: True
  gather_facts: False

  tasks:
  - name: Add Insights SCM Credential Into Tower
    tower_credential:
      name: Insights SCM Credential
    tower_credential:
      name: SCM Credential
      organization: Default
      state: present
      kind: scm
      username: joe
      password: secret
      ssh_key_data: "{{ lookup('file', '/tmp/id_rsa') }}"
      ssh_key_unlock: "passphrase"