---
- name: Register RHEL Host to RHN and Insights
  hosts: all
  become: True
  gather_facts: False
  
  tasks:
    - name: Register as user with password and auto-subscribe to available content.
      redhat_subscription:
        state: present
        username: "{{ username }}"
        password: "{{ password }}"
        auto_attach: true

    - name: Install Insights Client
      yum:
        name: insights-client
        state: latest

    - name: Register Insights Client to cloud.redhat.com
      command: insights-client --register