---
- name: Setup OpenSCAP on RHEL
  hosts: all
  become: True
  gather_facts: False
  
  tasks:
    - name: Install OpenSCAP Packages
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - openscap-scanner
        - scap-security-guide