---
- name: Setup OpenSCAP on RHEL
  hosts: all
  become: True
  gather_facts: False
  
  tasks:
    - name: Install OpenSCAP Packages
      yum:
        name: "{{ packages }}"
        state: latest
        vars:
          packages:
            - openscap-scanner
            - scap-security-guide