---
- name: Show Available OpenSCAP SSG Profiles 
  hosts: all
  become: True
  gather_facts: False
  
  tasks:
    - name: Find /var/log files equal or greater than 10 megabytes ending with .old or .log.gz
      find:
        paths: /usr/share/xml/scap/ssg/content/
        patterns: 'ssg-*-ds.xml'
      register: find.results

    - name: Print to Standard Output
      debug:
        msg: {{ find.results }}